language: python
sudo: False
install:
  - "pip install tox"
script:
  - "tox"
env:
  - "TOXENV=py35-1.11.X"
  - "TOXENV=py27-1.11.X"
  - "TOXENV=py35-1.10.X"
  - "TOXENV=py27-1.10.X"
  - "TOXENV=py35-1.9.X"
  - "TOXENV=py27-1.9.X"
  - "TOXENV=py34-1.8.X"
  - "TOXENV=py27-1.8.X"
  - "TOXENV=py34-1.7.X"
  - "TOXENV=py27-1.7.X"
  - "TOXENV=py34-1.6.X"
  - "TOXENV=py27-1.6.X"
  - "TOXENV=py34-1.5.X"
  - "TOXENV=py27-1.5.X"
  - "TOXENV=py27-1.4.X"
